language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- openjdk11
deploy:
  provider: releases
  api_key:
    secure: tsdAf42L5Yg+z2Wgj2rcABzuKxoLXD/7nm/M1cLIlynORrXUXuNWO34j8RaZykDtaW0lKsxlS2r09KbpQQw83WyU6ed6Iknjn4i30fQzShvi7MMFcBAoWnEJ4ibeH0rlEuDira7jVL9LsUYWwlKIPfLICN6a4zjCmXDFIDLwYSzY7jx+axeVv+zi6dY6daQ8GVQx4AxAyr7E0WYL6wTF5viOoZuIHp7wnwBQhJZxZcoL/RHVznzCk4iYrvDTMUrQd1aEHFyuL9vaK4xfY9mGA2qAL/Uqtu4oUxvhzUbdeRWWElvSVTMDUNT6RzEN7DrwEyuK+hHYXoXpgXmYUuEUoeNOBDbFImkCEHkCNoBIY2NuSJqzrlHpRpshJBcU0BQqODGXV3VXe2abKsuvWE0qp/amkyruebu0WvqXwdI8V11jfjeQs73ud9cHgjWksetnMEc6jY7GLFXfJQ3xYYng0shjIARTyHOGlnc8LTA/1ppUyyxFNhVWRKn7APXsoPJki4jqCChmUwz7TfQbfVRkxBBvZ8AVCiNEuiB4qghY2E0CRBAJ22so5PM0F6YRmMlWOm2v+ng5AvaONZzyQG/elYdghe9WUmqcY2sMAq/XpvUTz04aE6IqZcDhFsO70UUfYTnjk2KSDvxUSviygVfQJnp5J52VaLWLjqlaKi81CdA=
  file: target/spid-provider.jar
  skip_cleanup: true
  on:
    repo: nicolabeghin/keycloak-spid-provider
    tags: true
